version: '3.8'

services:

  web:
    restart: always
    build: .
    ports:
      - "40:80"
    depends_on:
      - db
    env_file:
      - .env

  db:
    restart: always
    image: mongo:latest
    volumes:
      - url_shortener_db:/data/db
    env_file:
      - .env

  proxy:
    image: caddy
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-data:/data
      - ./data/caddy-config:/config


volumes:
  url_shortener_db: